### ISSUE TITLE
Role icons & raid icons not showing

### ISSUE THREAD

**Issue by Brady84** [Toludin/Healium#14]
Doesn't show anything so I need another set of unitframes up so I can see who the tanks/healers are

**Comment by Toludin** [comment]
Are you using ElvUI's AddonSkins option, and do you have the AddonSkin for Healium turned on? I can reproduce this issue with that on, but once I turn it off I see raid icons just fine (can't test role icons just now but I imagine it's the same).

**Comment by Brady84** [comment]
^^ yeah, seems ElvUI enables it by default, once I unticked the box it seems to work just fine

**Comment by Toludin** [comment]
OK thanks for confirming, I'll try to file a bug with the AddonSkins addon to have them fix it.
