### ISSUE TITLE
Drag drop

### ISSUE THREAD

**Issue by xTAZx** [Toludin/Healium#15]
some of the healing spells are not on the list in setup, in other versions you could drag the spels from spellbook in to Healium but that dont work in this version anyting you are planing on fixing ?

**Comment by Toludin** [comment]
Drag and drop works fine for me - which class/spec are you on, which spell are you trying to drag, and are you seeing any errors?

**Comment by xTAZx** [comment]
hmm there whas a problem 2 days ago when i draged a spell it dittent wanna stick to Healium.. now that i made this post and you replied it sudently works..

thanks for your great work to get this addon work again i love to use it when i heal cant use any of the others ;) 

if you want you can delete this poste ;)

**Comment by Toludin** [comment]
Ah weird, well I'm glad it's working for you now. Will close this one out.
