### ISSUE TITLE
HoT and mana bars on frames not working

### ISSUE THREAD

**Issue by nimeuh** [Toludin/Healium#25]
Hey - I only have this version installed. The mana bars always appear full so when in raid I cant tell how the other peoples are doing on mana and I've always looked on it for my personal mana too instead of the top right corner and for some reason it just shows as full all the time. Also the HoT spells (renew) and Prayer of Mending are not showing up. 

In holy spec the cooldown animation works fine and in disc the buttons dont seem "pressed" ie the cooldown doesnt go off. 

Ive deleted the folders adn re downloaded them deveral times.. im not sure what to do, been healing with healium for years on Nimeu please help =(

**Comment by Gal10** [comment]
Hi

Delete healium from Twitch as well then delete the one you have currently on wow ( right click wow icon --properties--open file location---retail file---interface--addons.)
Then clone the last file on Code tab on this site. Download it ---open it---copy 'Healium-master' and paste it on addons (same file you opened before to delete old file). That's it 💃

**Comment by Toludin** [comment]
This was an issue I did have to fix a little while ago (back on July 18) so I do think you just had an older version. Hope it's working for you now!
