### ISSUE TITLE
Original autor Last seen april

### ISSUE THREAD

**Issue by Valdesca** [Toludin/Healium#26]
https://wow.curseforge.com/members/engypoo

**Comment by Toludin** [comment]
I know - I've tried to reach out to him many times, but to no avail :( And unfortunately, Twitch/Curse don't seem to feel 11 months is long enough to call his project 'abandoned,' so for now at least I'm afraid I can only host this update here. I'll keep trying every so often though to see if they're ok with me hosting this version on their site. I know it's a lot easier to keep updated via Twitch/Curse.
