### ISSUE TITLE
Mana bar infringes on Atonement/Shield buffs

### ISSUE THREAD

**Issue by Toludin** [Toludin/Healium#3]
When Atonements are on yourself and a shield they line up properly on the left side in line with the nameplate/health bar. But when placing a shield on another party member the mana bar slightly covers the shield and Atonements.

**Comment by omegaxnodle** [comment]
Upon future inspecting this may be related to the way the ElvUI handles it with the add-on '[addonskins](https://www.tukui.org/addons.php?id=3)' I haven't had a chance to try it on default, but it may have something to do with the way the add-on pads the side.

**Comment by omegaxnodle** [comment]
You can close this, not a bug with Healium, only was related to that addonskins, they line up perfect on standard.

**Comment by Toludin** [comment]
Sounds good, yea I've seen it as well on the addon when I have addonskins up. If you'd like, you might want to file a bug at https://git.tukui.org/Azilroka/AddOnSkins/issues.
