### ISSUE TITLE
Holy Shock/Glimmer of Light

### ISSUE THREAD

**Issue by Gal10** [Toludin/Healium#32]
Would it be possible to add the Glimmer of Light buff to show on targets frames?
Holy Shock leaves a Glimmer of Light on the target for 30 sec.  When you Holy Shock, all targets with Glimmer of Light are damaged for 1076 or healed for 1587.
It is really important for holy paladin to track it.
Thank you

**Comment by Gal10** [comment]
Found Something!
https://wago.io/jLdWckBhG  - makes the target frame sparkle every time it has a Glimmer on!

**Comment by Toludin** [comment]
Happy to add it in. Will be in the next build.
